[package]
name = "louds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
fid = "0.1.7"
fid-rs = "0.1.1"
newtype = "0.2.1"

[dev-dependencies]
pretty_assertions = "1.4.0"
